'use client';
import { useEffect, useMemo, useState } from 'react';
import { advanced, electives, Grade, Track } from '../lib/types';
import { readStudents, saveStudent, readRosterOverrides, readDeletedRosterIds } from '../lib/store';
type Roster={studentId:string;lastName:string;firstName:string;middleName:string;email?:string;grade:Grade};
export default function StudentForm(){
 const [step,setStep]=useState(1),[roster,setRoster]=useState<Roster[]>([]),[registeredIds,setRegisteredIds]=useState<string[]>([]),[done,setDone]=useState(''),[error,setError]=useState('');
 const [f,setF]=useState({firstName:'',lastName:'',studentId:'',email:'',phone:'',grade:'' as Grade|'',track:'' as Track|'',electives:[] as string[],advanced:[] as string[],observation:''});
 useEffect(()=>{fetch('/api/roster').then(r=>r.ok?r.json():Promise.reject()).then(setRoster).catch(()=>fetch('/api/students').then(r=>r.json()).then((base:Roster[])=>{const overrides=readRosterOverrides();const deleted=new Set(readDeletedRosterIds());const merged=base.filter(s=>!deleted.has(s.studentId)).map(s=>overrides.find(x=>x.studentId===s.studentId)||s);const extras=overrides.filter(s=>!base.some(x=>x.studentId===s.studentId));setRoster([...merged,...extras])})).catch(()=>setError('No se pudo cargar la lista de estudiantes.'));fetch('/api/submissions?ids=1').then(r=>r.ok?r.json():Promise.reject()).then((items:{studentId:string}[])=>setRegisteredIds(items.map(s=>s.studentId))).catch(()=>setRegisteredIds(readStudents().map(s=>s.studentId)))},[]);
 const set=(key:string,value:string)=>setF(x=>({...x,[key]:value}));
 const chooseGrade=(grade:Grade)=>setF(x=>({...x,grade,studentId:'',firstName:'',lastName:''}));
 const chooseStudent=(id:string)=>{const s=roster.find(x=>x.studentId===id);if(s)setF(x=>({...x,studentId:s.studentId,firstName:[s.firstName,s.middleName].filter(Boolean).join(' '),lastName:s.lastName,email:s.email||''}))};
 const toggle=(key:'electives'|'advanced',name:string)=>{setError('');setF(x=>{const current=x[key];if(current.includes(name))return {...x,[key]:current.filter(n=>n!==name)};const limit=key==='electives'?2:4;if(current.length>=limit){setError(key==='electives'?'Solo puedes seleccionar 2 electivas.':'Puedes seleccionar hasta 4 cursos avanzados.');return x}return {...x,[key]:[...current,name]}})};
 const available=useMemo(()=>electives.filter(x=>x.grade===f.grade&&(!f.track||x.track==='Ambos'||x.track===f.track)),[f.grade,f.track]);
 const next=()=>{setError('');if(step===1&&(!f.grade||!f.studentId))return setError('Selecciona tu grado y tu nombre en la lista.');if(step===3&&!f.track)return setError('Selecciona tu bachillerato.');if(step===4&&f.electives.length!==2)return setError('Debes seleccionar exactamente dos electivas.');setStep(step+1)};
 const submit=async()=>{try{const id=crypto.randomUUID();const student={id,...f,grade:f.grade as Grade,track:f.track as Track,status:'Pendiente' as const,createdAt:new Date().toISOString()};const response=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(student)});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||'No se pudo guardar la selección.')}try{saveStudent(student)}catch{}setDone(id.slice(0,8).toUpperCase())}catch(e){setError((e as Error).message)}};
 if(done)return <div className="shell"><div className="card success"><div className="check">✓</div><h1>¡Selección registrada!</h1><p className="muted">Tu información fue recibida correctamente.</p><strong>Número de registro: {done}</strong><div><button className="btn primary" style={{marginTop:25}} onClick={()=>location.reload()}>Volver al inicio</button></div></div></div>;
 const registered=new Set([...registeredIds,...readStudents().map(s=>s.studentId)]),studentsForGrade=roster.filter(s=>s.grade===f.grade&&!registered.has(s.studentId));
 return <div className="shell"><section className="hero"><div className="eyebrow">Ciclo académico 2027</div><h1>Electivas 2027</h1><p>Selecciona tu nombre y completa tu selección. Cada estudiante puede enviar el formulario una sola vez.</p></section><div className="stepbar">{[1,2,3,4,5,6,7].map(n=><div key={n} className={'step '+(n<=step?'active':'')}/>)}</div><div className="card">
 <h2>{step===1?'Selecciona tu estudiante':step===2?'Datos del estudiante':step===3?'Tu bachillerato':step===4?'Elige tus electivas':step===5?'Observaciones':step===6?'Cursos avanzados':'Revisa tu selección'}</h2>
 {step===1&&<div className="formgrid"><div className="field"><label>Grado *</label><select value={f.grade} onChange={e=>chooseGrade(e.target.value as Grade)}><option value="">Selecciona tu grado</option><option value="11">11.º grado</option><option value="12">12.º grado</option></select></div><div className="field"><label>Estudiante *</label><select value={f.studentId} onChange={e=>chooseStudent(e.target.value)} disabled={!f.grade}><option value="">Selecciona tu nombre</option>{studentsForGrade.map(s=><option key={s.studentId} value={s.studentId}>{s.lastName}, {s.firstName}{s.middleName?' '+s.middleName:''} · ID {s.studentId}</option>)}</select>{f.grade&&studentsForGrade.length===0&&<small className="muted">No hay estudiantes disponibles: todos los de este grado ya completaron el formulario.</small>}</div><div className="field full"><label>Identificación seleccionada</label><input value={f.studentId?`${f.firstName} ${f.lastName} · ${f.studentId}`:''} readOnly placeholder="Se completará al elegir tu nombre"/></div></div>}
 {step===2&&<div className="formgrid"><div className="field"><label>Identificación</label><input value={f.studentId} readOnly/></div><div className="field"><label>Nombres y apellidos</label><input value={`${f.firstName} ${f.lastName}`} readOnly/></div><div className="field full"><label>Correo electrónico</label><input value={f.email||'Pendiente de agregar por administración'} readOnly/></div><p className="muted">Estos datos son informativos y serán completados o actualizados posteriormente por administración.</p></div>}
 {step===3&&<div className="choicegrid">{(['Ciencias','Humanidades'] as Track[]).map(t=><div className={'choice '+(f.track===t?'selected':'')} onClick={()=>set('track',t)} key={t}><strong>{t}</strong><small>Orientación de {t.toLowerCase()}</small></div>)}</div>}
 {step===4&&<><p className="muted">Selecciona exactamente 2 electivas para {f.grade}.º. Seleccionadas: {f.electives.length}/2.</p><div className="choicegrid">{available.map(s=><div className={'choice '+(f.electives.includes(s.name)?'selected':'')} onClick={()=>toggle('electives',s.name)} key={`${s.grade}-${s.name}`}><strong>{s.name}</strong><small>{s.capacity} cupos disponibles</small></div>)}</div></>}
 {step===5&&<div className="field"><label>Observaciones</label><p className="muted" style={{margin:'0 0 4px',fontSize:13}}>En caso de no quedar en ninguna de las electivas seleccionadas, ¿cuál es tu otra opción?</p><textarea value={f.observation} onChange={e=>set('observation',e.target.value)}/></div>}
 {step===6&&<><p className="muted">Puedes seleccionar hasta 4 cursos avanzados. Seleccionados: {f.advanced.length}/4.</p><div className="choicegrid">{advanced.filter(s=>s.track==='Ambos'||s.track===f.track).map(s=><div className={'choice '+(f.advanced.includes(s.name)?'selected':'')} onClick={()=>toggle('advanced',s.name)} key={s.name}><strong>{s.name}</strong><small>Curso avanzado · cupos sujetos a disponibilidad</small></div>)}</div></>}
 {step===7&&<div className="summary"><div><span>Estudiante</span><strong>{f.firstName} {f.lastName}</strong></div><div><span>Grado</span><strong>{f.grade}.º · {f.track}</strong></div><div><span>Electivas</span><strong>{f.electives.join(', ')||'No aplica'}</strong></div><div><span>Cursos avanzados</span><strong>{f.advanced.join(', ')||'Ninguno'}</strong></div><div className="field full"><span>Observación</span><strong>{f.observation||'Sin observaciones'}</strong></div></div>}
 {error&&<div className="error">{error}</div>}<div className="actions">{step>1&&<button className="btn secondary" onClick={()=>setStep(step-1)}>← Atrás</button>}<button className="btn primary" onClick={step===7?submit:next}>{step===7?'Confirmar selección':'Continuar →'}</button></div></div></div>;
}
